<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Beanie quantity_cartac1dd209cbcc5e5d1_550fff</name>
   <tag></tag>
   <elementGuidId>a734e98a-52b9-4b11-9aaf-1cbe19112416</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='quantity_62ceaf3a80145']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#quantity_62ceaf3a80145</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>87a1c08a-b962-4716-ab62-a46562da8371</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>number</value>
      <webElementGuid>3680373c-a077-4ca7-b0b7-7b95d7643201</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>quantity_62ceaf3a80145</value>
      <webElementGuid>81e67c5e-280e-41bf-bfbb-f91de114b0c9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>input-text qty text</value>
      <webElementGuid>eb85ef25-01d6-46cd-a00a-ac17f1982157</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>step</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>ec939359-cd91-4814-89b4-a39a4b19c693</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>min</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>fa1ad285-ca0e-4db0-b031-7405dc2ab87d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>cart[ac1dd209cbcc5e5d1c6e28598e8cbbe8][qty]</value>
      <webElementGuid>31c3891d-769f-447a-ad67-beb3b6dfc982</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>6d12b724-a725-49bd-a02a-96180b2fc9d1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Qty</value>
      <webElementGuid>b695e081-bad0-4321-875e-ace1d76ffaf6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>4</value>
      <webElementGuid>f676ec01-b7c6-4377-994b-8b9d5567a2f8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>inputmode</name>
      <type>Main</type>
      <value>numeric</value>
      <webElementGuid>826796f8-93da-4cf0-afe7-cc8b999ce827</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>cf524a28-9576-4f89-ab79-e91cfbff87da</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;quantity_62ceaf3a80145&quot;)</value>
      <webElementGuid>159ecca6-403d-446c-83e7-4fef55a73492</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='quantity_62ceaf3a80145']</value>
      <webElementGuid>53cdebbd-09b2-41cd-9450-5535074a8b3d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//article[@id='post-53']/div/div/form/table/tbody/tr[2]/td[5]/div/input</value>
      <webElementGuid>5b12c47f-fabe-4534-a23c-ced1c1468253</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[2]/td[5]/div/input</value>
      <webElementGuid>d163b913-994c-44b6-ad8d-f7d62c94bc1e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'number' and @id = 'quantity_62ceaf3a80145' and @name = 'cart[ac1dd209cbcc5e5d1c6e28598e8cbbe8][qty]' and @title = 'Qty']</value>
      <webElementGuid>cc34a4c3-0709-4ddd-915e-9f89159b9c9a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
